-- 019_retailer_requests_table.sql
-- New table backing the user-submitted retailer-request form Frontman
-- is shipping at /request-retailer in the ammoraccoon-web app. Each
-- row is one visitor saying "please add retailer X to your tracker."
--
-- Why a table at all (vs. an email or a Google Form): keeping
-- submissions in the same database means we can sort by demand
-- (COUNT(*) by retailer_name) when prioritizing the next scraper to
-- write. Bible-aligned: build what users actually want next, not what
-- we guess they want. The 5 inactive-retailer rows audited 2026-05-10
-- (Academy Sports, Cabela's, Bereli, Optics Planet, Bulk Munitions)
-- showed how silently a "wishlist" decays into noise without a feedback
-- loop; this table is the loop.
--
-- Field set agreed with Frontman:
--   retailer_name   (NOT NULL, 1-200 chars)  — the brand the user typed
--   retailer_url    (NOT NULL, 1-500 chars)  — homepage / storefront URL
--   why             (nullable, 0-500 chars)  — free-text "why this one"
--   contact_email   (nullable)               — opt-in for follow-up
--   created_at      (NOT NULL, default now())
--   id              (bigint identity PK)
--
-- RLS posture:
--   * INSERT for the anon role is open (WITH CHECK (true)) — the form
--     submits via the anon key, like every other public surface in
--     the app. No auth, no rate-limit at the DB layer (rely on
--     Cloudflare/Vercel for that if abuse appears).
--   * SELECT is restricted to service_role — Jon reads the queue via
--     the Supabase dashboard or a service-key script. Anon clients
--     cannot list other users' submissions; matches the operational
--     posture we'd want for any user-supplied PII like contact_email.
--   * No UPDATE / DELETE policy added — service_role bypasses RLS for
--     those operations when needed; anon cannot mutate.
--
-- Performance: an index on created_at DESC supports the obvious
-- "newest first" admin query. Once volume warrants, a second index
-- on lower(retailer_name) would help the demand-aggregation query
-- (GROUP BY retailer_name with case-folding); deferred until there's
-- enough data to bother.
--
-- Idempotency:
--   * CREATE TABLE IF NOT EXISTS — re-runs noop the table create.
--   * ALTER TABLE ... ENABLE ROW LEVEL SECURITY — re-enabling is a
--     no-op in Postgres.
--   * DROP POLICY IF EXISTS … ; CREATE POLICY … — standard idempotent
--     two-step (Postgres has no CREATE POLICY IF NOT EXISTS).
--   * CREATE INDEX IF NOT EXISTS — re-runs noop.
--   * Constraints wrapped in DO $$ … EXCEPTION WHEN duplicate_object …
--     blocks so re-runs don't crash on already-present constraints.
-- Safe to re-apply across environments.

CREATE TABLE IF NOT EXISTS retailer_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retailer_name TEXT        NOT NULL,
    retailer_url  TEXT        NOT NULL,
    why           TEXT,
    contact_email TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Sanity-check constraints. Wrapped so re-runs against an environment
-- where they already exist don't error.
DO $$ BEGIN
    ALTER TABLE retailer_requests
        ADD CONSTRAINT retailer_requests_name_length_chk
        CHECK (char_length(retailer_name) BETWEEN 1 AND 200);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE retailer_requests
        ADD CONSTRAINT retailer_requests_url_length_chk
        CHECK (char_length(retailer_url) BETWEEN 1 AND 500);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE retailer_requests
        ADD CONSTRAINT retailer_requests_why_length_chk
        CHECK (why IS NULL OR char_length(why) <= 500);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- "Newest first" admin query support.
CREATE INDEX IF NOT EXISTS retailer_requests_created_at_idx
    ON retailer_requests (created_at DESC);

-- RLS — enable, then declare policies. Both DROP-IF-EXISTS guards
-- make the policy declarations safe to re-run.
ALTER TABLE retailer_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS retailer_requests_anon_insert ON retailer_requests;
CREATE POLICY retailer_requests_anon_insert
    ON retailer_requests
    FOR INSERT
    TO anon
    WITH CHECK (true);

DROP POLICY IF EXISTS retailer_requests_service_select ON retailer_requests;
CREATE POLICY retailer_requests_service_select
    ON retailer_requests
    FOR SELECT
    TO service_role
    USING (true);

COMMENT ON TABLE retailer_requests IS
    'User-submitted retailer requests from /request-retailer in the '
    'ammoraccoon-web app. Anon may INSERT; only service_role may '
    'SELECT. Sort by COUNT(*) GROUP BY retailer_name to prioritize '
    'the next scraper to build.';
